    YOUR_LICENSE_KEY_HERE

server-ip: your-server-ip-here

guild: 1266820682960863282

# Command emoji ID.
command-emoji: 1348338860794319000

# NEW! Configure the pick intervals, 1 2 1 2 1 2 1 2 is the default.
# you can change it to 1 2 2 1 1 2 1 2 1
pick-intervals:
  - 1
  - 2
  - 1
  - 2
  - 1
  - 2
  - 1
  - 2

# NEW! Claim elo map.
# ROLE ID: ELO
claim-elo:
  1270669238696153110: 150
  1294923555581988864: 100
  1294923561705930825: 150
  1294923564142825503: 200
  1294920428233560115: 150
  1294920416858476585: 200
  1294780052008865812: 300
  1294929658936295465: 200
  1329384043124621402: 150
  1294988168604422246: 100

# Performance. This is experimental USE IF YOU HAVE A LOT OF RAM.
less-cpu-mode: true

#============================== GENERAL
# THIS IS PRECONFIGURED FOR MY TEST SERVER, YOU CAN CHANGE ANYTHING YOU WANT

# Bot's token
token: 

# Group where all arenas are
group: RBW

# Group where all 2v2 arenas are
group-2v2: RBW2V2

# Bot's status (ONLINE, IDLE, DO_NOT_DISTURB, INVISIBLE)
status: DO_NOT_DISTURB

# Your server's name
server-name: Celestial Ranked Bedwars

# Waiting room
waiting-room: 1294718038339227759

rolesync:
  13783968494881343450: trialt
  12947706445206691970: helpert
  12947706441978389430: modt
  12947706435643638680: srmodt
  12950460172799877530: admint
  12947706474187982210: developert
  12950396984098816000: managert
  13210242333875896420: leadershipt
  12947706340809155060: ownert
  12706692386961531100: celestet
  12947706467184845210: screensharert
  12947706467393209030: screensharert
  12949235555819888640: aurorat
  12949235641428255030: zenitht
  12949235617059308250: sovereignt
  12949881686044222460: mediat
  13210242333875896420: leadershipt
  13278817453365003240: eventt

tagsync:
  12949204282335601150: Pupst
  12949204168584765850: Pugst
  12947800520088658120: Premiumt


# Bot's prefix
prefix: =

# Alerts channel
alerts-channel: 1294718234129600512

# Elo prefix formatting, use %elo% for player elo
elo-formatting: "[%elo%] "

# With this role, you won't have the prefix formatting with the elo.
prefix-toggle-role: 1294943902863724555

# Registered role ID
registered-role: 1294724325579952294

game-logs: 1319913941698351137

# Starting elo
starting-elo: 0

#============================== EMBEDS

# Embed colors (you MUST use RGB values separated by ","):
default: 245,245,245
success: 245,245,245
error: 200,0,0

# Embed footers (leave blank to disable). Use {%version} to write bot's version, use {%name} to write your server's name that you set above
footer: "%name%"

footer-image: "https://cdn.discordapp.com/avatars/966381737691185172/47242c6d60f15f3e6acdb812c1601949.png?size=2048"

#============================== LOGGING

# Log every command players do?
log-commands: true
# Scoring Logs channel (helps you to know who executed =modify n stuff cmds)
scoring-logs-channel: 1319914095990018058

#============================== BANNING

# mininum vouches in strikerequest command to get a player striked.
min-vouches: 3

banned-role: 1294951233173327953

# Channel where the bans are announced, leave blank to disable announcing bans
ban-channel: 1294718230195077305

# Ban time for strikes (in hours)
strike1: 0
strike2: 2
strike3: 12
strike4: 24
# 5+
strike5: 48

#============================== SCREENSHARING

# How many images do people need to attach for proof when using the command?
ss-attachments: 1
frozen-role: 1294956996797267969
# SS Logs channel
ss-logs-channel: 1294718274868609035
# SS Category ID
ss-category: 1294718024934359120
# How many mins will ppl be automatically unfrozen in after getting ss requested
time-till-unfrozen: 10

# SSERS Roles IDS (you can add multiple roles separated by ",") Used for Mentions
ss-roles: 1294770646718484521,1294770646739320903

#============================== GAMES

game-channels-category: 1294718011126714430
game-vcs-category: 1294718013718925314

# use %number% to get game number
# use %mode% to get game mode (4v4 / 3v3 etc)
game-channel-names: "gameâ”ƒ%number%"

# use %number% to get game number
# use %mode% to get game mode (4v4 / 3v3 etc)
# use %team% to get the team number
game-vc-names: "Game #%number% T%team%"

# Games announcing channel (leave blank to disable)
games-announcing: 1294718232720310302

# Scored games announcing channel (leave blank to disable)
scored-announcing: 1294718232720310302

# Display text helping people to invite eachother to party (leave blank to disable)
party-invite-cmd: "/p invite"

# Game channel deleting time after its scored (in seconds)
game-deleting-time: 30

# How many screenshots do players have to attach when using =submit (for proof)
submitting-attachments: 1

# Role to ping when game gets submitted
scorer-role: noone

#============================== TEAMS SORTING SYSTEM

# Sorting is done like this by default:

# (Player elo / 100 * sort-by-elo) + (Player wins / 100 * sort-by-wins) + (Player WS / 100 * sort-by-ws) +
#  + (Player highest WS / 100 * sort-by-highestws) + (Player MVP / 100 * sort-by-mvp) + (Player WLR / 100 * sort-by-wlr)

# number that will the bot get from this ^ will be used to sort teams

# All the numbers below must be exactly 100 when added up
# 1st player will have a lower number than 2nd to make it more fair (since 1st can pick first)
# If you do not understand this system you can dm me, and I'll give you another values to paste but this preset makes things more fair

sort-by-elo: 25
sort-by-peakelo: 0
sort-by-wins: 10
sort-by-ws: 5
sort-by-highestws: 5
sort-by-losses: 0
sort-by-ls: 0
sort-by-highestls: 0
sort-by-games: 0
sort-by-mvp: 10
sort-by-wlr: 35

#================================= THEMES SYSTEM
themesmanager: 1295326858258288724
# themes manager role

#============================== LEADERBOARD IMAGE(S)

lb-face-size: 42
lb-face-pixels: 140,135
lb-fontsize: 32
lb-y-variation: 53
lb-elo-pixels: 480,170
lb-wins-pixels: 650,170
lb-losses-pixels: 820,170
lb-mvp-pixels: 985,170
lb-name-pixels: 187,170

#================================ PARTIES

# Elo cap for parties, set to true if you want to have an elo cap.
elo-cap-enabled: false

party-limit: 3

# Max elo for parties
elo-cap: 1000

#================================ MODIFIERS
# Percentage of modifier. Percentage will get removed from win and lose elo.
# Set to 0 if you don't want to modify how much elo they gain

# 2v2 modifier
doubles-modifier: 0

# partied players modifier
partyof2-modifier: 0
partyof3-modifier: 0
partyof4-modifier: 0

# elo bounties.

# channel to announce
bounties-channel: 1294718234129600512

# max elo gain from bounty cap.
bounties-cap: 10

# elo bounties. this is an example
#  elo-bounty:
#  per-winstreak:
#    1:
#      after: 10WS
#    give: 10ELO
#per-elo:
#  1:
#    after: 1000ELO
#    give: 10ELO
#  2:
#    between: 800-1000ELO
#    give: 5ELO
elo-bounty:
  per-winstreak:
    1:
      after: 10WS
      give: 10ELO
  per-elo:
    1:
      after: 1000ELO
      give: 10ELO
    2:
      between: 800-1000ELO
      give: 5ELO
elo-decay:
  # max time that a player won't play to get decayed:
  every-days: 300
  # Channel with elo-decay logs.
  announcements: 1294718234129600512

# Channel with daily leaderboard updates
leaderboard-updates: 1319915030958964808


guilds:
  min-gold: 8000

#channel id where the bot wont let the users use commands
blockedcommands:
  - 1294718209236402269


commandschannel: 1294718211174170675